language: php

sudo: false

matrix:
  include:
    - php: 8.2
    - php: 8.3
    - php: 8.4
    - php: 8.5
      env: COLLECT_COVERAGE=true

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; else vendor/bin/phpunit --no-coverage; fi

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
